name: Minecraft Server

on: workflow_dispatch

jobs:
  run-server:
    runs-on: ubuntu-latest

    steps:
      - name: Install Java
        run: sudo apt update && sudo apt install openjdk-17-jdk -y

      - name: Download Server
        run: |
          mkdir server
          cd server
          wget https://launcher.mojang.com/v1/objects/server.jar

      - name: Accept EULA
        run: |
          cd server
          echo "eula=true" > eula.txt

      - name: Run Server
        run: |
          cd server
          java -Xmx2G -Xms2G -jar server.jar nogui
